import { MOCK_GUESTS } from "@/lib/mockGuests";
import type { Guest, GuestReply } from "@/types/guest";

/**
 * TEMPORARY IN-MEMORY GUEST STORE — to be replaced by Supabase.
 *
 * This is module state and nothing more. It is the single place that owns the
 * guest list for an event, so the invite form, the dashboard and the door
 * scanner all read and write the same array instead of each importing
 * MOCK_GUESTS and drifting apart.
 *
 * WHAT THIS IS NOT: persistence. There is deliberately no localStorage, no
 * sessionStorage, no cookie and no fetch. The list lives as long as the loaded
 * JavaScript module does, which means **every reply is lost on a full page
 * reload** and the list reseeds from MOCK_GUESTS. A reply submitted on the
 * invite page is visible on the dashboard only within the same loaded app —
 * client-side navigation keeps this module alive, a hard reload does not.
 *
 * When Supabase lands, the four exported functions below become the seam: they
 * keep their signatures and their bodies become queries. Callers should not
 * need to change.
 */

/**
 * Replaced wholesale on every write rather than mutated, so the reference is a
 * usable snapshot for useSyncExternalStore — identity changes when, and only
 * when, the data does.
 */
let guests: readonly Guest[] = MOCK_GUESTS;

const listeners = new Set<() => void>();

function emit(): void {
  for (const listener of listeners) {
    listener();
  }
}

/** Subscribes to writes. Returns its own unsubscribe. */
export function subscribe(listener: () => void): () => void {
  listeners.add(listener);

  return () => {
    listeners.delete(listener);
  };
}

/** The current list. Stable between writes — safe to compare by reference. */
export function listGuests(): readonly Guest[] {
  return guests;
}

/** A reply as the invite form hands it over, before it becomes a Guest row. */
export interface NewReply {
  name: string;
  phone: string;
  status: GuestReply;
  /** Total people attending, including the guest. Always >= 1. */
  partySize: number;
  message: string;
  /** Generated by the caller in its event handler, never during render. */
  respondedAt: string;
}

/**
 * Counter rather than a random id, because a stable, ordered id makes the seam
 * to a database row obvious and keeps React keys predictable in tests.
 */
let sequence = 0;

/** Appends a guest's own reply to the list. Returns the row it created. */
export function addReply(reply: NewReply): Guest {
  sequence += 1;

  const guest: Guest = {
    id: `rsvp-${sequence}`,
    name: reply.name,
    phone: reply.phone,
    rsvp: reply.status,
    /*
      The form counts the guest themselves; a Guest row counts only the people
      they bring. Clamped, so a malformed party size can never produce a
      negative that would quietly subtract from the headcount.
    */
    accompanyingCount: Math.max(0, reply.partySize - 1),
    message: reply.message,
    respondedAt: reply.respondedAt,
    /* Replying is not arriving. */
    checkedIn: false,
    checkedInAt: null,
  };

  guests = [...guests, guest];
  emit();

  return guest;
}

/**
 * Marks a guest arrived, or clears it. `checkedInAt` carries the timestamp the
 * caller generated in its handler; passing null undoes the check-in.
 */
export function setCheckedIn(
  guestId: string,
  checkedInAt: string | null,
): void {
  guests = guests.map((guest) =>
    guest.id === guestId
      ? { ...guest, checkedIn: checkedInAt !== null, checkedInAt }
      : guest,
  );
  emit();
}
